### ISSUE TITLE
Dir arrangement

### ISSUE THREAD

**Issue by achingachris** [Timothy-Wangwe/Jarvis-Lee#1]
Yoo T
Learn how to arrange the files and folders as a good developer practice, also helps in deployments

**Comment by wwangwe** [comment]
Was following this structure [Structure](https://github.com/Timothy-Wangwe/Django-Project-Structure).
Open a Pull Request, I wanna see whats wrongly placed.

**Comment by wwangwe** [comment]
Arrangement restructed. All is Groot.
