### ISSUE TITLE
Models to handle Tests, Questions and Answers

### ISSUE THREAD

**Issue by wwangwe** [Timothy-Wangwe/Jarvis-Lee#3]
This first model **Subjects**, works perfectly. It stores different subjects eg. Mathematics, Science, Religion etc.
```python
from django.db import models
from django.core.validators import MaxLengthValidator
class Subject(models.Model):
    name = models.CharField(max_length = 20)
    symbol = models.CharField(max_length = 5)

    def __str__(self):
        return "%s" % (self.name)
  ```
The model **Test** is designed to store individual tests/quiezzes. I defines the subject to which it belongs, it maximum score and its number since a single subject can have several tests. It will also be the model that questions will relate to.
```python 
class Test(models.Model):
    test_number = models.CharField(max_length = 25, null = True)
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE
    )
    score = models.IntegerField()
    
    def __str__(self):
        return "%s" % (self.subject.name)
```
This model **Question** is now the beginning of the issue. It is linked to a Test.  
Its designed to accommodate a question statement and four multiple choices.
```python
class Question(models.Model):
    test = models.ForeignKey(
        Test,
        null = True,
        # default = "Some Test",
        on_delete = models.CASCADE
    )
    question_text = models.CharField(max_length = 255, null = True)
    choice_a      = models.CharField(max_length = 25, null = True)
    choice_b      = models.CharField(max_length = 25, null = True)
    choice_c      = models.CharField(max_length = 25, null = True)
    choice_d      = models.CharField(max_length = 25, null = True)

    def __str__(self):
        return "%s %s %s %s %s %s" % (
            self.test, 
            self.question_text, 
            self.choice_a, 
            self.choice_b, 
            self.choice_c, 
            self.choice_d
        )
```
This last model is supposed to store the answers to its related question.
```python
class Answer(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete = models.CASCADE,
    )
    solution = models.CharField(max_length = 10)
```
### Summary
Now this is the logic behind it.  
All these models are connected and are supposed to work in that the _ADMIN_ can add a subject say Mathematics, they then can add a test, say _MTH Test 1_. In the test, they can add multiple Questions say _"Which of the following numbers is odd?" and multiple choices say : 2, 3, 18, 0_ and then finally add a related Answer to each question.  
#### UI
Here is what it looks like. I however have not used `forms.py` to either generate or hernest the data on this page.
![Screenshot from 2020-05-23 22-27-33](https://user-images.githubusercontent.com/45900186/82738981-b1876980-9d44-11ea-8832-d68d20160677.png)

**Comment by achingachris** [comment]
What was the desired outcome

**Comment by wwangwe** [comment]
A model that holds a single question, multiple choices and a single correct answer. These three should be provided in the admin panel. Then if the correct choice is provided, we should be able to track it rather record it for later analysis.

**Comment by wwangwe** [comment]
I think I've just solved this issue.  
I had to separate the Question from the Choices; instead of defining how many Choices(4) we have, we let a each Choice live as a model so that we can have as many as possible.
```python
class Question(models.Model):
    test            = models.ForeignKey(Test, null = True, on_delete = models.CASCADE)
    question_text   = models.CharField(max_length = 255, null = True)

    class Meta:
        order_with_respect_to = 'test'

    def __str__(self):
        return "%s %s" % (self.test, self.question_text)
```
Each Answer will be obviously linked to a particular Question and it will also be defined as either Correct or not using a null boolean field. We use the `NullBooleanField` instead of just `BooleanField` so that we can accommodate only one True choice and several Unknown choices.  
**_Note that it is impossible to have more that one of either True or False, but it can have as many nulls/unknowns_**.
```python
class Answer(models.Model):
    question        = models.ForeignKey(Question, on_delete = models.CASCADE, related_name = "Answers")
    answer_text     = models.CharField(max_length = 255, null = True)
    is_correct      = models.NullBooleanField(default = None)

    class Meta:
        order_with_respect_to   = 'question'
        unique_together         = ('question', 'is_correct',)
        
```
